version: "3.8"
services:

  fastchat-controller:
    image: localagi/fastchat-controller:${FASTCHAT_VERSION:-main}
    environment:
      FASTCHAT_CONTROLLER_HOST: "0.0.0.0"

  fastchat-worker:
    image: localagi/fastchat-worker:${FASTCHAT_VERSION:-main}
    environment:
      FASTCHAT_CONTROLLER_ADDRESS: http://fastchat-controller:21001
      FASTCHAT_DEVICE: "cpu"
      MODEL_PATH: lmsys/fastchat-t5-3b-v1.0 
      # or to use a local model:
      # MODEL_PATH: "/models/fastchat-t5-3b-v1.0"
      FASTCHAT_WORKER_ADDRESS: http://fastchat-worker:21002
  ## use volumes to mount local models and use MODEL_PATH to provide an absolute path from internal /models      
  # volumes:
  #   - /path/to/local/models:/models
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
              
    depends_on:
      - fastchat-controller
      
  fastchat-api:
    image: localagi/fastchat-api:${FASTCHAT_VERSION:-main}
    environment:
      FASTCHAT_CONTROLLER_ADDRESS: http://fastchat-controller:21001
    ports:
      - "7500:7500"
    depends_on:
      - fastchat-controller

  fastchat-gradio:
    image: localagi/fastchat-gradio:${FASTCHAT_VERSION:-main}
    environment:
      FASTCHAT_GRADIO_HOST: 0.0.0.0
      FASTCHAT_CONTROLLER_ADDRESS: http://fastchat-controller:21001
      FASTCHAT_GRADIO_MODEL_LIST_MODE: reload
    ports:
      - "3000:3000"
    depends_on:
      - fastchat-controller   
