version: "3.8"
services:

  fastchat-controller:
    image: localagi/fastchat-controller:${FASTCHAT_VERSION:-main}
    environment:
      FASTCHAT_CONTROLLER_HOST: "0.0.0.0"

  fastchat-worker:
    image: localagi/fastchat-worker:${FASTCHAT_VERSION:-main}
    environment:
      FASTCHAT_CONTROLLER_HOST: fastchat-controller
      FASTCHAT_DEVICE: "cpu"
      MODEL_PATH: lmsys/fastchat-t5-3b-v1.0 
      # or to use another model:
      # MODEL_PATH: "/model/fastchat-t5-3b-v1.0"
    volumes:
      - /local/path/to/models:/models
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
              
    depends_on:
      - fastchat-controller
      
  fastchat-api:
    image: localagi/fastchat-api:${FASTCHAT_VERSION:-main}
    environment:
      FASTCHAT_CONTROLLER_HOST: fastchat-controller
    ports:
      - "7500:7500"
    depends_on:
      - fastchat-controller

  fastchat-gradio:
    image: localagi/fastchat-gradio:${FASTCHAT_VERSION:-main}
    environment:
      FASTCHAT_CONTROLLER_HOST: fastchat-controller
    ports:
      - "3000:3000"
    depends_on:
      - fastchat-controller   
