version: "3.8"
services:

  fastchat-controller:
    image: localagi/fastchat:${FASTCHAT_VERSION:-main}
    command: "/fastchat/entrypoint.sh fastchat.serve.controller --host ${FASTCHAT_CONTROLLER_HOST} --port ${FASTCHAT_CONTROLLER_PORT}"

  fastchat-worker:
    image: localagi/fastchat:${FASTCHAT_VERSION:-main}
    command: /fastchat/entrypoint.sh fastchat.serve.model_worker --host ${FASTCHAT_WORKER_HOST} --port ${FASTCHAT_WORKER_PORT} --controller-address ${FASTCHAT_CONTROLLER_ADDRESS} --worker-address ${FASTCHAT_WORKER_ADDRESS} --model-path ${MODEL_PATH} --num-gpus ${FASTCHAT_GPU_COUNT} --device ${FASTCHAT_DEVICE}
    volumes:
      - ${LOCAL_MODEL_DIR:-./models}:/models
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
              
    depends_on:
      - fastchat-controller
      
  fastchat-api:
    image: localagi/fastchat:${FASTCHAT_VERSION:-main}
    command: /fastchat/entrypoint.sh fastchat.serve.openai_api_server --host ${FASTCHAT_API_HOST} --port ${FASTCHAT_API_PORT} --controller-address ${FASTCHAT_CONTROLLER_ADDRESS}
    environment:
      FASTCHAT_CONTROLLER_ADDRESS: http://fastchat-controller:21001
    ports:
      - "${FASTCHAT_API_PORT}:${FASTCHAT_API_PORT}"
    depends_on:
      - fastchat-controller

  fastchat-gradio:
    image: localagi/fastchat:${FASTCHAT_VERSION:-main}
    command: /fastchat/entrypoint.sh fastchat.serve.gradio_web_server --host ${FASTCHAT_GRADIO_HOST} --port ${FASTCHAT_GRADIO_PORT} --controller-url ${FASTCHAT_CONTROLLER_ADDRESS} --model-list-mode ${FASTCHAT_GRADIO_MODEL_LIST_MODE}
    ports:
      - "${FASTCHAT_GRADIO_PORT}:${FASTCHAT_GRADIO_PORT}"
    depends_on:
      - fastchat-controller   
