name: Publish Docker images

on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  packages: write
  contents: read

jobs:

  call-docker-build-fastchat:
    uses: localagi/ai-dedicated-workflows/.github/workflows/operation-docker-build-publish.yml@v3
    with:
      registry-github-enable: false
      registry-repo-name: fastchat
      tags: |
        type=schedule
        type=ref,event=branch
        type=semver,pattern={{version}}
      build-args: |
        FASTCHAT_VERSION=${{ github.ref_name }}
      platforms: linux/amd64,linux/arm64/v8
    secrets: inherit
